### ISSUE TITLE
ARB 18.0 on Windows and MSVC

### ISSUE THREAD

**Issue by duhadler** [BrianGladman/arb#1]
Thank you for your quick response! I have downloaded the current version of your fork and will report back my experience asap.
A litte bit of background information: The appearance of Flint 2.6 has changed a lot of things, since ARB has now (hopefully) a stable backbone, also on Windows. The "a long is 32 bit on 64 bit Windows" nightmare has haunted both FLINT and ARB for years, and on ARB, unfortunately, it seems to be back. Using mingw64, the 32 bit build passes all tests, but the 64 bit build has multiple test failures, which so far seem to be very poorly understood.
My hope is that, using your build methodology, it will be possible to come up with a debugging environment in Visual Studio that will allow to truly understand what is happening and make the necessary corrections.
This could, in principle, also be done in mingw64, but is (in my mind) much harder to do. Also, my experience with using Eigen and Boost Math together with MPFR and ARB has taught me that the difference between the runtimes of mingw64 and MSVC can produce very different results both with regard to speed and stability (MSVC wins most of the time, but not always), and that errors which occur in one environment do not necessarily occur in the other (although they often do). My final goal is the MSVC build, since I want to use FLINT/ARB etc based DLLs with CPython and Matlab 64 bit, which precludes the use of mingw64.

**Comment by duhadler** [comment]
Luckily, it seems that the problems with the mingw64 64 build of ARB 18.0 have been solved (these were really, really unexpected bugs, as far as I can tell), so a new ARB 18.1 release will appear soon. I will focus my testing of your build system on this new version (so feedback might take a little longer).

**Comment by BrianGladman** [comment]
A lot more of the ARB build system is now working.  I believe the main ARB build is now fully working. I also think the building of the ARB tests works.  The code for automatically running the ARB tests is still work in progress but should not be too hard to get working.  If you intend to do ARB debugging in Visual Studio I do believe my build will be far superior to the CMAKE one.  I should also say that it  helps a lot to have you on board to independently test what I am doing.  Thanks also for the further details of what you are trying to do.

EDIT:  I believe the ARB build is now fully working. I need to update the documentation but it works in the same way that the FLINT build works.  All tests pass in Windows x64 (I don't test on x86 but I see no reason why there would be build failures).

**Comment by duhadler** [comment]
I have build the FLINT and ARB static libraries with your build system for 64 bit, and it worked like a charm. Thank you so much for your work! It makes using FLINT and ARB on MSVC so much easier! I have also tried these static libraries on some of my projects, and so far the impression is that everything is working as it should (but this is of course NOT a real, comprehensive test).

I do have, however, problems building and running the tests, both for FLINT and ARB. I get tons of linking errors LNK2001 (unresolved external symbol) from pthreads,  mpir, mpfr, lib_flint, and lib_arb. I have tried it from the system command prompt, and the Visual Studio command prompt: same result.

While I do not have a definitive explanation for it, it has occurred to me that a possible cause for this failure might be that for my purposes I need to downgrade the Target Platform Version from 10.0.18 to 8.1 and the Platform Toolset from Visual Studio 2019 (v142) to Visual Studio (v140), because for my projects other components, which I cannot change, require it. Apparently, combining static libraries which are that far apart in their versions (like 10.0 and 8.1 or v142 and v140) can often fail. 

Now I presume that the executable files that your system is building take Target Platform Version 10.0.18 and Platform Toolset 2019 (v142) for granted (which, frankly, would make a lot of sense). If this was the case, then this could explain the linking failure in my special setup, because my precompiled static archives would not be compatible with these more current Platform versions.

And now comes the big question: is it possible to modify/extend the build system for the tests to allow for such idiosyncrasies? I cannot really use an older compiler version of MSVC like 2015, because the C++ template handling of these earlier versions is inadequate for my purposes, but I need to be able to link against the older runtimes.

Any thoughts?

**Comment by BrianGladman** [comment]
> I have build the FLINT and ARB static libraries with your build system for 64 bit, and it worked like a charm. Thank you so much for your work! It makes using FLINT and ARB on MSVC so much easier! I have also tried these static libraries on some of my projects, and so far the impression is that everything is working as it should (but this is of course NOT a real, comprehensive test).
> 
> I do have, however, problems building and running the tests, both for FLINT and ARB. I get tons of linking errors LNK2001 (unresolved external symbol) from pthreads, mpir, mpfr, lib_flint, and lib_arb. I have tried it from the system command prompt, and the Visual Studio command prompt: same result.
> 
> While I do not have a definitive explanation for it, it has occurred to me that a possible cause for this failure might be that for my purposes I need to downgrade the Target Platform Version from 10.0.18 to 8.1 and the Platform Toolset from Visual Studio 2019 (v142) to Visual Studio (v140), because for my projects other components, which I cannot change, require it. Apparently, combining static libraries which are that far apart in their versions (like 10.0 and 8.1 or v142 and v140) can often fail.
Yes, that is almost certainly the cause since my whole build system expects absolute consistency between the builds of the component libraries - mpir, mpfr, flint, arb and pthreads.   
> 
> Now I presume that the executable files that your system is building take Target Platform Version 10.0.18 and Platform Toolset 2019 (v142) for granted (which, frankly, would make a lot of sense). If this was the case, then this could explain the linking failure in my special setup, because my precompiled static archives would not be compatible with these more current Platform versions.
> 
> And now comes the big question: is it possible to modify/extend the build system for the tests to allow for such idiosyncrasies? I cannot really use an older compiler version of MSVC like 2015, because the C++ template handling of these earlier versions is inadequate for my purposes, but I need to be able to link against the older runtimes.

I'm sorry but there is no way I can modify the build system to allow mixing in the way I think you want. It is designed in every detail to bring together the component parts when they are all built by the same version of Visual Studio (any version on or after VS2013).   It would be a massive change and the chances are that I could never get it working and certainly never be able to test the huge number of configurations that such a build system would be capable of producing.
> 
> Any thoughts?

Can you not simply generate and build all the component libraries using the desired earlier version of Visual Studio and then build and run the FLINT and ARB tests with this same version?  The Python codes for building and running the tests both take an input parameter that is the Visual Studio version to use so they should work if you do this (but I have to admit that don't test this).

**Comment by duhadler** [comment]
Makes sense. Part of the issue might be that I am still using quite old builds (albeit recent versions) of mpir, mpfr and pthreads. Will build everything from scratch and then report back.

**Comment by duhadler** [comment]
So I rebuild MPIR and MPFR from scratch as static libs using the VS 2019 setup. In doing so, I failed to get MPIR working in the form it is currently published on your Github site. Does it work smoothly at your end? I had to go back to an archived version which I had downloaded on 2020-APR-03, where everything worked as expected, and all tests passed (or were skipped) as expected.

Here are my results for FLINT and ARB:

FLINT:
1978 tests:
        1976 ran correctly
        2 failed
Failed:
fmpz_lll: t-lll_mpf ...ERROR 3221226505 lll_mpf....
fmpz_lll: t-lll_mpf_with_removal ...ERROR 3221226505 lll_mpf_with_removal....

ARB:
813 tests:
        813 ran correctly

That's not too bad! I have no idea what causes the 2 failures on FLINT, and I will not pretend that I understand the error message. Everything considered, this is very encouraging.

Finally, I would like to add a personal note, if I may:
I have been following your work on multivariate computing using MSVC since your first GMP ports which preceded the publication of MPIR. The early and easy successes which I had building on your work have changed my attitude towards numerical computing completely and have encouraged me to try new ways which I would otherwise never have tried. The work done by the GMP/MPIR, MPFR, MPC, FLINT and ARB teams is fantastic in its own right, but without your contribution all of this would be inaccessable on Windows in 64 bit from CPython, Matlab and Java (R is the only relevant exception, where mingw64 not only works, but is needed). This is really something to be proud of.

**Comment by BrianGladman** [comment]
All the builds, including MPIR work fine here.  When you built MPIR, did you run mpir_config.py to update the VS build files for the configuration(s) that you are using?   Can you say more about the way in which it failed?     I am sure we can fix this with enough information about why it happens.

The FLINT failures are almost certainly not failures.  I have noticed that the way I run the tests with a Python driver will very occasionally cause an exception during a test.  I haven't tracked down why this happens but it is fairly rare.  When I run the test that fails manually I have always found that the failing test passes.  I suggest you do the same by finding the tests and running the ones that report failures to see if they pass when run manually.

Thank you for your kind words  which I much appreciate - its always encouraging when I can see what I have done has made a difference!

**Comment by duhadler** [comment]
So I followed your suggestion and ran the LLL test code separatly. This is the result

```
heuristic_dot....PASS
lll....PASS
lll_d....PASS
lll_d_heuristic....PASS
lll_d_heuristic_with_removal....PASS
lll_d_with_removal....PASS
lll_d_with_removal_knapsack....PASS


lll_mpf....FAIL (randintrel): basis matrices not equal!
[[12 -62 -52 50 -32 -70 59 -82 -124 0 -18]
[-106 -8 32 4 -102 -111 -63 9 -50 -54 -37]
[59 107 -18 140 92 83 13 -6 -80 -77 0]
[-52 73 -16 -31 80 -188 -1 47 -57 -25 -6]
[38 9 92 -49 3 132 -68 -44 -47 37 92]
[-163 -59 -70 54 44 -26 -60 43 85 63 52]
[134 136 -67 29 -18 74 -11 146 -24 53 87]
[58 -32 75 119 50 94 64 151 -18 -51 126]
[34 34 -78 -153 -47 73 80 -143 173 -155 32]
[-58 64 2 -134 -159 139 225 69 -125 204 -118]
][[12852270800782456176079689 2554837160720625478894997 747240708937826516509798 -1563306220014663369962119 25714761238751113998933 1834067529528572169745183 -611103737673850025888723 -82 -124 0 -18]
[17224618318872330676970448 -280408956664458895041216 -82014224151712666084217 171582390001609394264514 -2822351843277560351050 -201300094704355483151518 67072361452007930248233 9 -50 -54 -37]
[19390720078904402170981084 186939304442972597108850 54676149434475110861206 -114388260001072929344203 1881567895518374320531 134200063136236988364220 -44714907634671954356536 -6 -80 -77 0]
[13589853437098139340711756 -1464357884803285336245703 -428296503903388368977472 896041370008404615675795 -14738948514893930513840 -1051233827900523071803593 350266776471596966830059 47 -57 -25 -6]
[-10222850859775929044240174 1370888232581799038544721 400958429186150813739672 -838847240007868150833085 13798164567134744662276 984133796332404578227846 -327909322654260989731938 -44 -47 37 92]
[-21319669308499440529485908 -1339731681841303604441876 -391845737613738295495489 819782530007689328186293 -13484569917881681172095 -961767119143031747746826 320456838048482330705617 43 85 63 52]
[-3886042792905449433323286 -4548856408112333170369609 -1330452969572227699916053 2783447660026107951886813 -45784818790947106274371 -3265534869648433375219268 1088062752443684191826550 146 -24 53 87]
[4741188097421616206889043 -4704639161814810334141558 -1376016427434290293467257 2878771210027002060694128 -47352792037212419244128 -3377368255595297531966973 1125325175472577485999226 151 -18 -51 126]
[-13869155023068144628718372 4455386755890846872789038 1303114894854990145170500 -2726253530025571487877339 44844034843187917834604 3198434838080314882238769 -1065705298626348215886710 -143 173 -155 32]
[5983733057065986237353095 -2149802001094184856300279 -628775718496463775921013 1315464990012338689985589 -21638030798461307297053 -1543300726066725361325702 514221437798727460512370 69 -125 204 -118]
]


lll_mpf_with_removal....FAIL (randintrel): basis matrices not equal!
[[12 -62 -52 50 -32 -70 59 -82 -124 0 -18]
[-106 -8 32 4 -102 -111 -63 9 -50 -54 -37]
[59 107 -18 140 92 83 13 -6 -80 -77 0]
[-52 73 -16 -31 80 -188 -1 47 -57 -25 -6]
[38 9 92 -49 3 132 -68 -44 -47 37 92]
[-163 -59 -70 54 44 -26 -60 43 85 63 52]
[134 136 -67 29 -18 74 -11 146 -24 53 87]
[58 -32 75 119 50 94 64 151 -18 -51 126]
[34 34 -78 -153 -47 73 80 -143 173 -155 32]
[-58 64 2 -134 -159 139 225 69 -125 204 -118]
][[12852270800782456176079689 2554837160720625478894997 747240708937826516509798 -1563306220014663369962119 25714761238751113998933 1834067529528572169745183 -611103737673850025888723 -82 -124 0 -18]
[17224618318872330676970448 -280408956664458895041216 -82014224151712666084217 171582390001609394264514 -2822351843277560351050 -201300094704355483151518 67072361452007930248233 9 -50 -54 -37]
[19390720078904402170981084 186939304442972597108850 54676149434475110861206 -114388260001072929344203 1881567895518374320531 134200063136236988364220 -44714907634671954356536 -6 -80 -77 0]
[13589853437098139340711756 -1464357884803285336245703 -428296503903388368977472 896041370008404615675795 -14738948514893930513840 -1051233827900523071803593 350266776471596966830059 47 -57 -25 -6]
[-10222850859775929044240174 1370888232581799038544721 400958429186150813739672 -838847240007868150833085 13798164567134744662276 984133796332404578227846 -327909322654260989731938 -44 -47 37 92]
[-21319669308499440529485908 -1339731681841303604441876 -391845737613738295495489 819782530007689328186293 -13484569917881681172095 -961767119143031747746826 320456838048482330705617 43 85 63 52]
[-3886042792905449433323286 -4548856408112333170369609 -1330452969572227699916053 2783447660026107951886813 -45784818790947106274371 -3265534869648433375219268 1088062752443684191826550 146 -24 53 87]
[4741188097421616206889043 -4704639161814810334141558 -1376016427434290293467257 2878771210027002060694128 -47352792037212419244128 -3377368255595297531966973 1125325175472577485999226 151 -18 -51 126]
[-13869155023068144628718372 4455386755890846872789038 1303114894854990145170500 -2726253530025571487877339 44844034843187917834604 3198434838080314882238769 -1065705298626348215886710 -143 173 -155 32]
[5983733057065986237353095 -2149802001094184856300279 -628775718496463775921013 1315464990012338689985589 -21638030798461307297053 -1543300726066725361325702 514221437798727460512370 69 -125 204 -118]
]

lll_with_removal....PASS
wrapper....PASS
wrapper_with_removal....PASS
wrapper_with_removal_knapsack....PASS
```

Only code involving the mpf numerical type is failing. In the result matrix, the last 4 entries in each row are correct, and the rest is completely wrong. Looking at the source code in mpf2_lll.c, the interesting statement seems to be in line 71:

```
mpf_set_d(mpf_mat_entry(A->appSP2, i, j), DBL_MIN);
```

As far as I can tell, the mpf_set_d function does not have its own test code in MPIR, so I have no direct way of telling whether there is a problem in my MPIR build with this particular function, which would then cause this failure in FLINT.

The mpf data type is rarely used these days, and I do not know what made the FLINT team use it here. But it would be nice to track down this failure. Would it be possible to introduce dedicated tests for the mpf_set_d function in MPIR?


With regard to my failure to get the recent Github version of MPIR working, I will open a separate comment.

**Comment by BrianGladman** [comment]
That's a shame - I was not expecting that!   Since these pass for me there must be something different but we should get MPIR fully working for you first in case this is the cause of the FLINT failures.

**Comment by duhadler** [comment]
I agree that we should have the same results unless my MPIR build (or general Windows configuration) is severely broken. But one thing that we could be doing differently is for which target we are building MPIR. I am targeting k8, static lib. What are you targeting? I could build for the same target and see what happens.

**Comment by duhadler** [comment]
This is my attempt to use the current MPIR:

I start with a freshly downloaded mpir from your Github account, and open a command prompt. This is the result:

```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\dietrichhadler>cd C:\Extra\MSVC\mpir\msvc

C:\Extra\MSVC\mpir\msvc>python mpir_config.py 19
Traceback (most recent call last):
  File "mpir_config.py", line 52, in <module>
    join(solution_dir, 'version_info.py'))
  File "mpir_config.py", line 30, in write_f
    if exists(opath) and isfile(opath) and cmp(ipath, opath):
NameError: name 'isfile' is not defined

C:\Extra\MSVC\mpir\msvc>
```

If I start by deleting all subdirectories which start with ```vs``` and then run ```python mpir_config.py 19```, then I get into the list of options, but I do not think that this is how it is intended to be.

**Comment by BrianGladman** [comment]
That's easy to fix - its a bug on my part - sorry - on the line

from os.path import join, split, splitext, isdir, exists

early in the file, change it to:

from os.path import join, split, splitext, isdir, isfile, exists

**Comment by duhadler** [comment]
Thank you for your quick response and revision of MPIR on Github!

After a fresh download of the latest MPIR version, on my system the first steps now work as exspected. For a VS 2019 build, I have selected core2, haswell, k8, sandybridge. 

lib_mpir_gc and lib_mir_cxx build without errors. However, lib_mpir_core2, lib_mpir_haswell, lib_mpir_k8 and lib_mpir_sandybridge all fail with similar error messages. I am showing the error message for the lib_mpir_k8 build below:

```
1>------ Rebuild All started: Project: lib_mpir_k8, Configuration: Release x64 ------
1>building MPIR for k8 (x64) from directory mpn\x86_64w\k8
1>creating mpir.h for x64
1>creating config.h from vs19\cdata\mpn\x86_64w\k8\
1>Assembling add_err1_n.asm ==> x64\Release\add_err1_n.obj
1>C:\Extra\MSVC\mpir\msvc\vsyasm.targets(81,5): error MSB3721: The command ""C:\Program Files\yasm"\vsyasm.exe -Xvc -f x64 -g cv8 -i "..\..\..\mpn\x86_64w\\" -o "x64\Release\mpn\add_err1_n.obj" -rnasm -pnasm   ..\..\..\mpn\x86_64w\k8\add_err1_n.asm" exited with code 1.
1>Done building project "lib_mpir_k8.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

The error message is clearly related to vsyasm, and my first thought was of course that something is wrong with my vsyasm setup. However, the funny thing is that everything is working fine when using the MPIR Github version from 2020-APR-03.

Of course, I am not totally stuck, because I can continue using the 2020-APR-03 version of MPIR. However, this might nonetheless point to some problem with my overall configuration, which I currently do not see.

With the latest, fresh MPIR version from Github, can you build lib_mpir_core2, lib_mpir_haswell, lib_mpir_k8 and lib_mpir_sandybridge from scratch at your end?

**Comment by BrianGladman** [comment]
I have just tested the build for lib_mpir_k8 at my end and it builds without any errors.  But the fact that the earlier dated repository build works suggests that it is an error I have introduced recently.  I will have a look at the changes I have made recently and see if anything might explain this.   

The easiest way of debugging this will be to use mpir_config.py to generate the lib_mpir_k8.vcproj  file using the earlier working version, save it, then do this again using the current repository version and then compare the two generated *.vcproj files to see what has changed.    You don't need to use them to build mpir as we just need to see what has changed between the two generated *.vcproj files. 

If you attach the two versions here I will take a look at them.  I should mention that I am travelling today so there will be about four hours (around 10:00 to 14:00 BST - British Summer Time ) when I won't be able to respond here.

**Comment by duhadler** [comment]
I have compared the *.vcproj files, and they are just the same, except the Project-Guid, as one would expect. The *.vcproj.filters files are identical. The problem is elsewhere, and most likely somewhere in my Windows and/or Visual Studio and/or vsyasm setup. I really do not want to waste your time with that, but rather thank you for your help so far!

Enjoy the British summer!

**Comment by BrianGladman** [comment]
I have finished my travel now so I am happy to help further if you need any assistance.   It is worth checking where vsyasm is getting its configuration files from - these should be those in the mpir\msvc sub-directory: (vsyasm.props, vsyasm.targets and vsyasm.xml).

**Comment by PeterLuschny** [comment]
Hi Brian!

May I join the discussion? I'm seemingly trying to do exactly the same thing as duhadler.

The projects dll_mpir_gc, lib_mpir_cxx and lib_mpir_gc are created without errors. 
All with msvc\vs19 on Windows10Pro Ver. 1903.

However in the projects of add-test-lib errors occur. In particular note the path "\...\mpir\msvc\vs19\x64\Debug\\add-test-lib.lib".
There are two backslashes in "Debug\\add-test-lib.lib" (which I strangely enough cannot see here in the preview. An autocorrection of the BitHub-editor?) 

* Fehler MSB3073 Der Befehl "cd ..\..\..\ check_config x64 Debug 19 :VCEnd" wurde mit dem Code 1 beendet. add-test-lib C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets 139

* Fehler LNK1104 Datei "\...\mpir\msvc\vs19\x64\Debug\\add-test-lib.lib" kann nicht geöffnet werden. try ...\mpir\msvc\vs19\mpir-tune\try\LINK 1

* Fehler MSB3721 Der Befehl ""C:\Program Files\yasm"\vsyasm.exe -Xvc -f x64 -o "x64\Debug\sqr_basecase.obj" -rnasm -pnasm   sqr_basecase.asm" wurde mit Code 1 beendet. tune ...\mpir\msvc\vsyasm.targets 81

Thanks!

**Comment by PeterLuschny** [comment]
Oh, sorry, I'm on the wrong train. Actually I am interested in ARB, but my way there led me to MPIR and then I forgot to change the repository. Sorry again.

**Comment by BrianGladman** [comment]
Hi Peter, No need to apologise.  But if you are having an issue building MPIR it would be better to discuss it on my MPIR repository.   It looks like you are trying to build 'tune' in debug mode - this doesn't work since it only makes sense to tune MPIR when in Release mode.
